#!/bin/sh
#
# Usage:
#
#    sh install.sh
#
# Environment variables: VERBOSE, CP, LN, MKDIR, RM, DIRNAME, XARGS.
#
#    env VERBOSE=1 sh install.sh
#
# DO NOT EDIT THIS FILE
# 
# This file is generated by rcm(7) as:
#
#   rcup -x up.sh -x README.md -x install.sh -x Brewfile -x macos.sh -x spectacle.json -B 0 -g
#
# To update it, re-run the above command.
#
: ${VERBOSE:=0}
: ${CP:=/bin/cp}
: ${LN:=/bin/ln}
: ${MKDIR:=/bin/mkdir}
: ${RM:=/bin/rm}
: ${DIRNAME:=/usr/bin/dirname}
: ${XARGS:=/usr/bin/xargs}
verbose() {
  if [ "$VERBOSE" -gt 0 ]; then
    echo "$@"
  fi
}
handle_file_cp() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $CP -R "$1" "$2"
}
handle_file_ln() {
  if [ -e "$2" ]; then
    printf "%s " "overwrite $2? [yN]"
    read overwrite
    case "$overwrite" in
      y)
        $RM -rf "$2"
        ;;
      *)
        echo "skipping $2"
        return
        ;;
    esac
  fi
  verbose "'$1' -> '$2'"
  $DIRNAME "$2" | $XARGS $MKDIR -p
  $LN -sf "$1" "$2"
}
handle_file_ln "/Users/kyleespinola/.dotfiles/gitconfig" "/Users/kyleespinola/.gitconfig"
handle_file_ln "/Users/kyleespinola/.dotfiles/gitconfig.local" "/Users/kyleespinola/.gitconfig.local"
handle_file_ln "/Users/kyleespinola/.dotfiles/gitignore" "/Users/kyleespinola/.gitignore"
handle_file_ln "/Users/kyleespinola/.dotfiles/pryc" "/Users/kyleespinola/.pryc"
handle_file_ln "/Users/kyleespinola/.dotfiles/rcrc" "/Users/kyleespinola/.rcrc"
handle_file_ln "/Users/kyleespinola/.dotfiles/tags" "/Users/kyleespinola/.tags"
handle_file_ln "/Users/kyleespinola/.dotfiles/tmux.conf" "/Users/kyleespinola/.tmux.conf"
handle_file_ln "/Users/kyleespinola/.dotfiles/vimrc" "/Users/kyleespinola/.vimrc"
handle_file_ln "/Users/kyleespinola/.dotfiles/zshrc" "/Users/kyleespinola/.zshrc"
